uint64 timestamp			# time since system start (microseconds)
uint32 device_id                	# unique device ID for the sensor that does not change between power cycles
uint32 depth
float32 speed				# the speed being reported by the sensor
float32 temperature			# temperature reported in degrees Celsius
uint16 measurement_date			# Date relative to UTC time
uint32 measurement_time			# Time as 24 hour clock, UTC time
uint32 total_cumulative_distance	# Total cumulative distance traveled
uint32 distance_since_reset		# Distance traveled since last device reset
